### ISSUE TITLE
[build] - Transform plugins

### ISSUE THREAD

**Issue by rkovalyov** [AviVahl/ts-tools#162]
Is there way somehow apply plugin for transform files ? 
Target is renaming `scss` import to `css` after successfully compiling `js`. 
I want to run concurrently for ex. building `css` by `gulp` with `node-sass`

Or better to play with `@ts-tools/transpile` before running build script ?

Sorry for a lot of question, hope u are doing best :)

**Comment by AviVahl** [comment]
Since `@ts-tools/build` only has a CLI interface (`ts-build`), and there's no standard way of pointing tooling to custom transformers, I didn't add support for applying transformations.

You could probably use the `@ts-tools/transpile` package to do stuff programmatically, passing in the `"transformers"` option to `transpileCached`. Much more manual, but then you have full control.

I find that in the more complex use cases, using typescript's API directly might be the better choice (unless you need the added caching layer).

**Comment by AviVahl** [comment]
"build" package has now been removed from repository. last published one still available from `npm`.
